# Use case configuration for Fairphone 5
# Author: Luca Weiss <luca.weiss@fairphone.com>

Syntax 3

SectionUseCase."HiFi" {
	File "/Fairphone/fp5/HiFi.conf"
	Comment "Play HiFi quality music"
}

SectionUseCase."Voice Call" {
	File "/Fairphone/fp5/VoiceCall.conf"
	Comment "Make a phone call"
}
