# Use case configuration for Fairphone 5
# Author: Luca Weiss <luca.weiss@fairphone.com>

SectionVerb {
	EnableSequence [
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value.TQ "HiFi"
}

SectionDevice."Speaker" {
	Comment "Speaker Playback"

	Value {
		PlaybackChannels 2
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackVolume "Amplifier Playback Volume"
	}
}

SectionDevice."Mic1" {
	Comment "Built-in Microphone"

	Include.wcdmice.File "/codecs/wcd938x/AnalogMic1EnableSeq.conf"
	Include.wcdmicd.File "/codecs/wcd938x/AnalogMic1DisableSeq.conf"
	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/SoundwireMic0EnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"

	EnableSequence [
		cset "name='TX_DEC0 Volume' 84"
	]

	Value {
		CaptureChannels 1
		CapturePriority 200
		CapturePCM "hw:${CardId},1"
		CaptureMixerElem "ADC1"
		CaptureVolume "ADC1 Volume"
	}
}

# SectionDevice."HDMI" {
# 	Comment "HDMI/DisplayPort playback"
# 	EnableSequence [
# 		cset "name='DISPLAY_PORT_RX Audio Mixer MultiMedia1' 1"
# 	]
# 	DisableSequence [
# 		cset "name='DISPLAY_PORT_RX Audio Mixer MultiMedia1' 0"
# 	]
# 	Value {
# 		PlaybackPriority 200
# 		PlaybackPCM "hw:${CardId},0"
# 		JackControl "HDMI Jack"
# 	}
# }
