# VoiceCall use case for Fairphone 5
# L = earpiece (top)

SectionVerb {
	EnableSequence [
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 1"
		cset "name='QUIN_MI2S_RX Voice Mixer VoiceMMode1' 1"
		cset "name='VoiceMMode1 Capture Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 0"
		cset "name='QUIN_MI2S_RX Voice Mixer VoiceMMode1' 0"
		cset "name='VoiceMMode1 Capture Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value {
		TQ "VoiceCall"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker Playback"

	EnableSequence [
		cset "name='Amplifier L Profile Set' Receiver"
		cset "name='Amplifier R Profile Set' Receiver"

		exec "systemctl --user start dummystreamhack@Rhw:${CardId},8"
	]

	DisableSequence [
		exec "systemctl --user stop dummystreamhack@Rhw:${CardId},8"

		cset "name='Amplifier R Profile Set' Music"
		cset "name='Amplifier L Profile Set' Music"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		PlaybackPriority 250

		PlaybackMixer "default:${CardId}"
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece Playback"

	EnableSequence [
		cset "name='EAR_RDAC Switch' 1"

		# Make L/Top quieter
		cset "name='Amplifier L PCM Playback Volume' 250"
		# Make R/bottom silence/mute
		cset "name='Amplifier R PCM Playback Volume' 0"

		cset "name='Amplifier L Profile Set' Receiver"
		cset "name='Amplifier R Profile Set' Receiver"

		exec "systemctl --user start dummystreamhack@Rhw:${CardId},8"
	]

	DisableSequence [
		exec "systemctl --user stop dummystreamhack@Rhw:${CardId},8"

		cset "name='Amplifier R Profile Set' Music"
		cset "name='Amplifier L Profile Set' Music"

		cset "name='Amplifier R PCM Playback Volume' 360"
		cset "name='Amplifier L PCM Playback Volume' 360"

		cset "name='EAR_RDAC Switch' 0"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		# Make audio to mono during usage of Earpiece
		PlaybackChannels 1

		PlaybackPriority 300

		PlaybackMixer "default:${CardId}"
	}
}


SectionDevice."Microphone" {
	Comment "Bottom Microphone"

	EnableSequence [
		cset "name='TX DEC0 MUX' SWR_MIC"
		cset "name='TX SMIC MUX0' SWR_MIC0"

		cset "name='TX_AIF1_CAP Mixer DEC0' 1"
		cset "name='TX_DEC0 Volume' 84"

		cset "name='ADC1_MIXER Switch' 1"
		cset "name='ADC1 Switch' 1"

		exec "systemctl --user start dummystreamhack@Thw:${CardId},8"
	]

	DisableSequence [
		exec "systemctl --user stop dummystreamhack@Thw:${CardId},8"

		cset "name='ADC1_MIXER Switch' 0"
		cset "name='ADC1 Switch' 0"

		cset "name='TX SMIC MUX0' ZERO"
		cset "name='TX_AIF1_CAP Mixer DEC0' 0"
	]

	Value {
		CapturePCM "hw:${CardId},1"
		CapturePriority 200
		CaptureMixerElem "ADC1"
	}
}
