# VoiceCall use case for Fairphone 5
# L = earpiece (top)

SectionVerb {
	EnableSequence [
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 1"
		cset "name='QUIN_MI2S_RX Voice Mixer VoiceMMode1' 1"
		cset "name='VoiceMMode1 Capture Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 0"
		cset "name='QUIN_MI2S_RX Voice Mixer VoiceMMode1' 0"
		cset "name='VoiceMMode1 Capture Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value {
		TQ "VoiceCall"
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece Playback"

	EnableSequence [
		# Make L/Top quieter
		cset "name='Amplifier L PCM Playback Volume' 250"
		# Make R/bottom silence/mute
		cset "name='Amplifier R PCM Playback Volume' 0"

		cset "name='Amplifier L Profile Set' Receiver"
		cset "name='Amplifier R Profile Set' Receiver"

		exec "systemctl --user start dummystreamhack@Rhw:${CardId},7"
	]

	DisableSequence [
		exec "systemctl --user stop dummystreamhack@Rhw:${CardId},7"

		cset "name='Amplifier R Profile Set' Music"
		cset "name='Amplifier L Profile Set' Music"

		cset "name='Amplifier R PCM Playback Volume' 360"
		cset "name='Amplifier L PCM Playback Volume' 360"
	]

	Value {
		# Make audio to mono during usage of Earpiece
		PlaybackChannels 1
		PlaybackPriority 300
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackVolume "Amplifier L PCM Playback Volume"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker Playback"

	Value {
		PlaybackChannels 2
		PlaybackPriority 250
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackVolume "Amplifier Playback Volume"
	}
}

SectionDevice."Mic1" {
	Comment "Bottom Microphone"

	Include.wcdmice.File "/codecs/wcd938x/AnalogMic1EnableSeq.conf"
	Include.wcdmicd.File "/codecs/wcd938x/AnalogMic1DisableSeq.conf"
	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/SoundwireMic0EnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"

	EnableSequence [
		cset "name='TX_DEC0 Volume' 84"

		exec "systemctl --user start dummystreamhack@Thw:${CardId},7"
	]

	DisableSequence [
		exec "systemctl --user stop dummystreamhack@Thw:${CardId},7"
	]

	Value {
		CaptureChannels 1
		CapturePriority 200
		CapturePCM "hw:${CardId},1"
		CaptureMixerElem "ADC1"
		CaptureVolume "ADC1 Volume"
	}
}
